USE master
GO
IF DB_ID(N'University') IS NOT NULL
DROP DATABASE University;
GO

CREATE DATABASE University
GO

USE University

CREATE TABLE Groups(
	GroupId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GroupName NVARCHAR(10) NOT NULL
)

CREATE TABLE Students(
    StudentId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Surname NVARCHAR(15) NOT NULL,
	Name NVARCHAR(12) NOT NULL,
	MiddleName NVARCHAR(20) NOT NULL,
	Gender NVARCHAR(7) NOT NULL,
	DateOfBirth DATE NOT NULL,
	GroupId INT FOREIGN KEY REFERENCES Groups(GroupId) NOT NULL
)

CREATE TABLE Exams(
	ExamId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AssessmentForm NVARCHAR(1) NOT NULL,
	SubjectName NVARCHAR(15) NOT NULL,
	ExamDate DATE NOT NULL,
	Session NVARCHAR(1) NOT NULL,
	GroupId INT FOREIGN KEY REFERENCES Groups(GroupId) NOT NULL
)

CREATE TABLE Grades(
	GradeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ExamId INT FOREIGN KEY REFERENCES Exams(ExamId) NOT NULL,
	StudentId INT FOREIGN KEY REFERENCES Students(StudentId) NOT NULL,
	Grade INT NOT NULL
)
