USE master
GO
IF DB_ID(N'UniversityNew') IS NOT NULL
DROP DATABASE UniversityNew;
GO

CREATE DATABASE UniversityNew
GO

USE UniversityNew

CREATE TABLE Groups(
	GroupId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GroupName NVARCHAR(10) NOT NULL,
	Specialty NVARCHAR(50) NOT NULL
)

CREATE TABLE Students(
    StudentId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Surname NVARCHAR(15) NOT NULL,
	Name NVARCHAR(12) NOT NULL,
	MiddleName NVARCHAR(20) NOT NULL,
	Gender NVARCHAR(7) NOT NULL,
	DateOfBirth DATE NOT NULL,
	GroupId INT FOREIGN KEY REFERENCES Groups(GroupId)
)

CREATE TABLE Exams(
	ExamId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AssessmentForm NVARCHAR(1) NOT NULL,
	SubjectName NVARCHAR(15) NOT NULL,
	ExamDate DATE NOT NULL,
	Session NVARCHAR(1) NOT NULL,
	GroupId INT FOREIGN KEY REFERENCES Groups(GroupId) ON DELETE CASCADE,
	TeacherSurname NVARCHAR(15) NOT NULL,
	TeacherName NVARCHAR(12) NOT NULL,
	TeacherMiddleName NVARCHAR(20) NOT NULL
)

CREATE TABLE Grades(
	GradeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ExamId INT FOREIGN KEY REFERENCES Exams(ExamId) ON DELETE CASCADE,
	StudentId INT FOREIGN KEY REFERENCES Students(StudentId) ON DELETE CASCADE,
	Grade INT NOT NULL
)
